[package]
name = "rtsonlib"
version = "0.2.8"

[dependencies]
rustr = "*"
#rustson = { git = "https://github.com/tercen/rustson", tag = "0.2.8" }
rustson = { path = "../rustson" }

[lib]
name = "rtsonlib"
crate-type = ["staticlib","rlib"]
